If TestBase.expect() is passed an assert message, pass it along when delegating to TestBase.runCmd() to execute the debugger command.  This will result in a more semantic assert message than just the command failed message like before:
AssertionError: False is not True : Command 'thread list' returns successfully

And now, we will have:

AssertionError: False is not True : Process state is stopped due to breakpoint